In [2]:
import numpy as np


In [6]:
a = np.array([[0, 1, 2, 3],[4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
#da un errore, devono essere dello stesso tipo gli array

In [7]:
a = np.array([[0,  2, 3],[4, 5, 6, 7]])
a

array([list([0, 2, 3]), list([4, 5, 6, 7])], dtype=object)

In [9]:
b = np.array([[0, 1, 2, 3],[4, 5, 6, 7]])
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [10]:
b.shape #dimensione della matrice

(2, 4)

In [13]:
b[1,3] #restituisce il valore

7

In [14]:
b[1,3]= 8
b
#cambia il valore

array([[0, 1, 2, 3],
       [4, 5, 6, 8]])